[package]
name = "circuit"
type = "bin"
authors = [""]

[dependencies]
noir_rsa = { git = "https://github.com/zkpassport/noir_rsa", tag = "v0.7.0-1" }
bignum = {tag = "v0.6.1", git = "https://github.com/noir-lang/noir-bignum"}
